### ISSUE TITLE
Commands not refreshing?

### ISSUE THREAD

**Issue by dragonfire1119** [PhiloNL/artisan-remote#1]
I was checking this out with adding the commands after adding the application & the commands only show up when I remove the site/re-add it. I can't see the source code on the companion app to see what's going on? Wish the companion app was open source 👍

**Comment by PhiloNL** [comment]
Hi @dragonfire1119 
Thanks for checking Artisan Remote out 😄  Sorry for the delay, I didn't receive a notification.
I'll see what I can do in regards to make the companion app open source in the near future by replacing the commercial Tailwind UI components.

I've just released a new version that will refresh all your applications every when you start the application or when you navigate to the overview of all your applications. If you are on Mac the app should auto update (if it's in your applications directory). Otherwise you can download v1.0.1 [here](https://unlock.sh/download/a428d391-79a8-4300-b7f7-ace69518525b).

If you have any other questions or feature requests let me know 🙌

**Comment by dragonfire1119** [comment]
@PhiloNL Thank you for fixing it so fast. It was Holiday's no problem man! Trying it out.
